### ISSUE TITLE
Music/Live TV not playing when proxy is enabled

### ISSUE THREAD

**Issue by laleeroy** [dragonflylee/switchfin#82]
### Describe the bug

Works fine if proxy option is disabled

[Info] cplayer: Playing [url]
[Error] MPVCore => FILE ERROR: unrecognized file format
[Info] MPVCore  => EVEMT_START_FILE
[ERROR] cplayer: Failed to recognize file format

### To reproduce

Play audio in home or in media library 

### Operating system

19.0.1|AMS 1.8.0|E

### Jellyfin Server

10.9.11 Docker

**Comment by dragonflylee** [comment]
Thanks for feedback, Fixed in latest [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

you need to reconfigure the proxy address in setting, as the config struct changed

**Comment by laleeroy** [comment]
> Thanks for feedback, Fixed in latest [![nightly](https://camo.githubusercontent.com/8cf6f501ec9d5e03280249459dbcfeecc2e2c81186380bc615b41c2773717551/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)
> 
> you need to reconfigure the proxy address in setting, as the config struct changed

Hi, I jist tested it and it doesn't fix the Music/audio playing, now even the Movies/Seroes doesn't play anymore

**Comment by dragonflylee** [comment]
@laleeroy did you reconfigure the **proxy address** in setting ?

**Comment by laleeroy** [comment]
> @laleeroy did you reconfigure the **proxy address** in setting ?

Yes I did reconfigure it, now when playing Movies/Series, the "Play error" pop up/dialogue is appearing

**Comment by dragonflylee** [comment]
maybe you need to delete `/switch/Switchfin/config.json` then reconfigure all settings

**Comment by laleeroy** [comment]
> maybe you need to delete `/switch/Switchfin/config.json` then reconfigure all settings

Shoot, I have been configuring it wrong all along, I remove the http:// in the proxy, I thought it is fine since I was able to comnect to the server.
Anyway, the music play is still not starting

ffmpeg: failed to resolve hostname [url]: Ni address associated with hostname

**Comment by dragonflylee** [comment]
sorry it's my fault, please try this version https://nightly.link/dragonflylee/switchfin/actions/runs/11811576775

**Comment by laleeroy** [comment]
> sorry it's my fault, please try this version https://nightly.link/dragonflylee/switchfin/actions/runs/11811576775

Hello again, sorry for my bad English but it's not the audio that it doesn't work but the Music, also I noticed that the Live TV from Jellyfin server doesn't play aswell when proxy is enabled, I have tried the latest build from the actions page.

When playing live tv from Jellyfin server, it pop up the error message and I got this warn ffmpeg: httproxy HTTP error 400 Bad request 
When playing music I have this error MPVCore unrecognized file format and also cplay: Failed to recognize file format

**Comment by dragonflylee** [comment]
@laleeroy please confirm you switchfin version is **v0.5.3-8fbe705** in about dialog from setting tab.
mp3 music play ok in my 10.8.13 jellyfin server

**Comment by laleeroy** [comment]
> @laleeroy please confirm you switchfin version is **v0.5.3-8fbe705** in about dialog from setting tab. mp3 music play ok in my 10.8.13 jellyfin server

Hi, my switchfin ver is 0.5.3-8fbe075 (Deko3d).
May I ask what you put in host name after enabling the proxy option? I will try to emulate your setting, right now in my testing it is set to http://g.g and proxied to http://localip:8096

**Comment by dragonflylee** [comment]
in my setting , proxy addr is `http://192.168.1.7:1080` and jellyfin server is `http://192.168.1.7:8096`

proxy using https://github.com/SagerNet/sing-box

**Comment by laleeroy** [comment]
> in my setting , proxy addr is `http://192.168.1.7:1080` and jellyfin server is `http://192.168.1.7:8096`
> 
> proxy using https://github.com/SagerNet/sing-box

Hmmmm, I don't know sing-box, but do I actually need to setup a proxy like maybe nginx? I thought it is fine as is because movies and series is playing well

**Comment by dragonflylee** [comment]
please try https://nightly.link/dragonflylee/switchfin/actions/runs/11880062283 
i found another mistake which cause track load failed

sorry for waste your time

**Comment by laleeroy** [comment]
> please try https://nightly.link/dragonflylee/switchfin/actions/runs/11880062283 i found another mistake which cause track load failed
> 
> sorry for waste your time

Hi, I dont have a switch anymore so I tested it with the windows version of the app.
The music plays, but the live tv from the server doesnt, thanks for your work btw!
![debug](https://github.com/user-attachments/assets/79571b8b-c333-44fe-84c5-70ffa177507f)

**Comment by laleeroy** [comment]
> please try https://nightly.link/dragonflylee/switchfin/actions/runs/11880062283 i found another mistake which cause track load failed
> 
> sorry for waste your time

Sorry for the ping, just got a new switch, I installed the latest build from the actions section, and the live tv and music seems to work now when proxy is enabled.
Thanks!
